/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barcodes;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Student_report extends javax.swing.JFrame {
    String card=Fine_add.cardno;
    /**
     * Creates new form Student_report
     */
    public Student_report() {
        initComponents();
        try
        {
            DefaultTableModel dt=new DefaultTableModel();
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/barcode","root","");
           
           String []col={"AMOUNT","DATE","FINE_TYPE","STATUS"};
           dt.setColumnIdentifiers(col);
           tb1.setModel(dt);
           
           String q1="select * from transaction where card_no='"+card+"'";
           Statement stmt1=con.createStatement();
           ResultSet rs1=stmt1.executeQuery(q1);
           
           int i;
           for(i=1;i<=5;i++)
           {
               while(rs1.next())
               {
                   Vector v=new Vector();
                   v.add(rs1.getString("AMOUNT"));
                   v.add(rs1.getString("DATE"));
                   v.add(rs1.getString("FINE_TYPE"));
                   v.add(rs1.getString("STATUS"));
                   dt.addRow(v);
               }
           }
           
           String q2="select * from fine where card_no='"+card+"' and status='not paid'";
           Statement stmt2=con.createStatement();
           ResultSet rs2=stmt2.executeQuery(q2);
           while(rs2.next())
           {
               t2.setText(rs2.getString("AMOUNT"));
               t3.setText(rs2.getString("FINE_TYPE"));
           }
           
           String q3="select * from issue where card_no='"+card+"'";
           Statement stmt3=con.createStatement();
           ResultSet rs3=stmt3.executeQuery(q3);
           while(rs3.next())
           {
               t1.setText(rs3.getString("AMOUNT"));
           }
        }
        catch(Exception ex)
        {System.out.println(ex);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Last 5 Transactions");

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tb1);

        jLabel2.setText("Amount");

        jLabel3.setText("Fine type");

        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(t3))
                .addGap(18, 18, 18)
                .addComponent(t1)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try
        {
            SimpleDateFormat sdf=new SimpleDateFormat("dd/mm/yyyy");
            java.util.Date d=new java.util.Date();
            String dt=sdf.format(d);
            
            card=Card_add.card_no;
            String a=t2.getText();
            int amt=Integer.parseInt(a);
            String finetype=t3.getText();
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/barcode","root","");
             String q1="select * from issue wher card_no='"+card+"'";
             Statement stmt1=con.createStatement();
             ResultSet rs1=stmt1.executeQuery(q1);
             
             String tot="";
             while(rs1.next())
             {
                 tot=rs1.getString("AMOUNT");
             }
             int total=Integer.parseInt(tot);
             if(total>=amt)
             {
                 int b=total -amt;
                 String bal=b+"";
                 String q2="update issue set AMOUNT='"+bal+"' where card_no='"+card+"'";
                 Statement stmt2=con.createStatement();
                 int rs2=stmt2.executeUpdate(q2);
                 if(rs2!=0)
                 {
                     System.out.println("fine paid.....");
                     JOptionPane.showMessageDialog(null,"fine paid.....");
                 }
                 
                 String q3="insert into transaction values('"+card+"','"+a+"','"+dt+"','"+finetype+"','Paid')";
                 Statement stmt3=con.createStatement();
                 int rs3=stmt3.executeUpdate(q3);
                 
                 String q4="update fine set status='Paid' where card_no='"+card+"' ";
                 Statement stmt4=con.createStatement();
                 int rs4=stmt4.executeUpdate(q4);
             }
             else
             {
                 JOptionPane.showMessageDialog(null,"You are not having enough balance to pay the Fine.");
             }
             
        }
        catch(Exception ex)
        {System.out.println(ex);}// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
